// KaggleRecipeImporter.swift
// Reads stocked_kaggle_recipes.json from the app bundle and seeds RecipeDatabase.
// Up to 1500 quality-scored recipes with category + cuisine inference.
// JSON generated by kaggle_to_stocked.py from the Kaggle dataset:
// https://www.kaggle.com/datasets/pes12017000148/food-ingredients-and-recipe-dataset-with-images
//
// SETUP: Drag stocked_kaggle_recipes.json into Xcode → check "Add to targets"
// NO other code changes needed — seeds automatically at first launch.

import Foundation
import os

// MARK: - Kaggle Import Models

private struct KaggleExport: Decodable {
    let version: Int
    let source:  String
    let count:   Int
    let recipes: [KaggleRecipe]
}

private struct KaggleRecipe: Decodable {
    let title:       String
    let description: String
    let sourceURL:   String
    let sourceName:  String
    let prepTime:    String
    let cookTime:    String
    let totalTime:   String
    let servings:    String
    let category:    String
    let cuisine:     String
    let tags:        [String]
    let ingredients: [String]
    let steps:       [String]
    let imageName:   String
}

// MARK: - Importer

@MainActor
final class KaggleRecipeImporter {
    static let shared = KaggleRecipeImporter()
    // #13: store the seeded data VERSION, not just a bool. When the bundled JSON ships
    // a higher `version`, we re-seed automatically (incremental update on app update).
    private let seedVersionKey = "kaggleSeedVersion"

    /// Call once at launch. Re-seeds only when the bundled dataset version increases.
    func importIfNeeded() async {
        guard let url = Bundle.main.url(forResource: "stocked_kaggle_recipes", withExtension: "json") else {
            Log.data.notice("Recipe seed JSON not bundled; skipping seed")
            return
        }

        do {
            let data   = try Data(contentsOf: url)
            let export = try JSONDecoder().decode(KaggleExport.self, from: data)

            // #13: skip only if we've already seeded this version or newer.
            let seededVersion = UserDefaults.standard.integer(forKey: seedVersionKey)
            guard export.version > seededVersion else {
                Log.data.debug("Recipe seed up to date (v\(seededVersion, privacy: .public))")
                return
            }

            // #12: de-duplicate the incoming batch (fuzzy) before seeding.
            let deduped = RecipeDedup.dedupe(export.recipes,
                                             title: { $0.title },
                                             ingredients: { $0.ingredients })

            var imported = 0
            for recipe in deduped {
                guard !recipe.title.isEmpty, !recipe.ingredients.isEmpty else { continue }
                let entry = RecipeDatabaseEntry(
                    title:       recipe.title,
                    description: recipe.description,
                    sourceURL:   recipe.sourceURL,
                    sourceName:  recipe.sourceName.isEmpty ? "Kaggle Food Dataset" : recipe.sourceName,
                    prepTime:    recipe.prepTime,
                    cookTime:    recipe.cookTime,
                    totalTime:   recipe.totalTime,
                    servings:    recipe.servings,
                    // #20: normalize to the canonical taxonomy so filters/dedup agree.
                    category:    RecipeTaxonomy.canonicalCategory(recipe.category),
                    cuisine:     RecipeTaxonomy.canonicalCuisine(recipe.cuisine),
                    tags:        recipe.tags,
                    ingredients: recipe.ingredients,
                    steps:       recipe.steps
                )
                await RecipeDatabase.shared.upsert(entry)
                imported += 1
            }

            UserDefaults.standard.set(export.version, forKey: seedVersionKey)
            Log.data.notice("Seeded \(imported, privacy: .public) recipes (dataset v\(export.version, privacy: .public))")

        } catch {
            // #8: resilient + observable — a malformed/missing bundle no longer fails silently.
            Log.data.error("Recipe seed failed: \(error.localizedDescription, privacy: .public)")
        }
    }

    /// Force re-import (e.g. after updating the bundled JSON with a new CSV run).
    func resetAndReimport() async {
        UserDefaults.standard.removeObject(forKey: seedVersionKey)
        await importIfNeeded()
    }
}
